spring.application.name=JavaDemo2
# Cấu hình kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLySanPham2;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;
spring.datasource.username=sa
spring.datasource.password=48691412
# Cấu hình Hibernate (Tự động cập nhật bảng và hiện log SQL)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.datasource.driverClassName=org.postgresql.Driver